server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_trade?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: root
    password: jiangjie06.
  sql:
    init:
      mode: always
      encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yjj.campustradeplatform.entity
  configuration:
    map-underscore-to-camel-case: true
